from tkinter import *
from tkinter import ttk
from tkinter import messagebox

from sqlite import Database

db = Database("balance.db")
root=Tk()
root.title("STUDENT DETAILS")
root.config(bg="#8A8A2B")
root.geometry("1366x700+0+0")
root.state("zoomed")

name=StringVar()
userid=StringVar()
contactno=StringVar()
department=StringVar()
gender = StringVar()
year=StringVar()

eframe=Frame(root,bg="#8A8A2B")
eframe.pack(side=TOP,fill=X)
title=Label(eframe,text="STUDENT DETAILS",font=("Aerial",18,"bold"),bg="#A5A52A")
title.grid(row=0,columnspan=2,sticky="w",padx=10,pady=10)

lbname=Label(eframe,text="NAME",font=("Aerial",12),bg="#A5A52A",fg="black")
lbname.grid(row=1,column=0,sticky="W",padx=10,pady=10)
txtname=Entry(eframe,textvariable="name",font=("Aerial",12),bg="#FFFFFF",width=30)
txtname.grid(row=1,column=1,sticky="W",padx=10,pady=10)
lbuserid=Label(eframe,text="REG ID",font=("Aerial",12),bg="#A5A52A",fg="black")
lbuserid.grid(row=2,column=0,sticky="W",padx=10,pady=10)
txtuserid=Entry(eframe,textvariable="userid",font=("Aerial",12),bg="#FFFFFF",width=30)
txtuserid.grid(row=2,column=1,sticky="W",padx=10,pady=10)
lbcontactno=Label(eframe,text="CONTACTNO",font=("Aerial",12),bg="#A5A52A",fg="black")
lbcontactno.grid(row=3,column=0,sticky="W",padx=10,pady=10)
txtcontactno=Entry(eframe,textvariable="contactno",font=("Aerial",12),bg="#FFFFFF",width=30)
txtcontactno.grid(row=3,column=1,sticky="W",padx=10,pady=10)
lbdepartment=Label(eframe,text="DEPARTMENT",font=("Aerial",12),bg="#A5A52A",fg="black")
lbdepartment.grid(row=4,column=0,sticky="W",padx=10,pady=10)
txtdepartment=ttk.Combobox(eframe,textvariable="department",font=("Aerial",12),width=28,state="readonly")
txtdepartment['values']=("Computer Science","Information Technology","SoftwareSystem","Computer Technology")
txtdepartment.grid(row=4,column=1,sticky="W",padx=10,pady=10)
lbgender = Label(eframe,text="GENDER",font=("Aerial",12),bg="#A5A52A",fg="black")
lbgender.grid(row=5,column=0,sticky="W",padx=10,pady=10)
txtgender = Radiobutton(eframe,text = "MALE",variable = gender,value= "MALE", bg="#A5A52A")
txtgender.grid(row=5,column=1,sticky="w",padx=10,pady=10)
txtgender1 = Radiobutton(eframe,text = "FEMALE",variable = gender,value="FEMALE",bg="#A5A52A")
txtgender1.grid(row=5,column=2,sticky="w",padx=10,pady=10)
lbyear=Label(eframe,text="YEAR",font=("Aerial",12),bg="#A5A52A",fg="black")
lbyear.grid(row=6,column=0,sticky="w",padx=10,pady=10)
txtyear=ttk.Combobox(eframe,textvariable="year",font=("Aerial",12),width=28,state="readonly")
txtyear['values']=("I","II","III","IV","V")
txtyear.grid(row=6,column=1,sticky="w",padx=10,pady=10)
def getData(event):
 selected_row = tv.focus()
 data = tv.item(selected_row)
 global row
 row=data['values']
 name.set(row[1])
 userid.set(row[2])
 contactno.set(row[3])
 department.set(row[4])
 gender.set(row[5])
 year.set(row[6])
def displayall():
 tv.delete(*tv.get_children())
 for row in db.fetch():
  tv.insert("", END, values=row)
def add_command():
 db.insert(txtname.get(),txtuserid.get(), txtcontactno.get(), txtdepartment.get(), gender.get(),txtyear.get())
 print(gender.get())
 messagebox.showinfo("Success", "Record Inserted")
 clearall_command()
 displayall()
def update_command():
 db.update(row[0],txtname.get(),txtuserid.get(),txtcontactno.get(),txtdepartment.get(),gender.get(), txtyear.get())
 messagebox.showinfo("Success", "Record Updated")
 clearall_command()
 displayall()
def delete_command():
 db.remove(row[0])
 clearall_command()
 displayall()
def clearall_command():
 txtname.delete(0,END)
 txtuserid.delete(0,END)
 txtcontactno.delete(0,END)
 txtdepartment.set("")
 txtyear.set("")

bframe=Frame(eframe,bg="#8A8A2B")
bframe.grid(row=7,column=0,columnspan=4,sticky="w",padx=10,pady=10)
addbutton=Button(bframe,text="ADD",bg="#FFFF40",fg="#FFA500",command=add_command)
addbutton.grid(row=0,column=0,padx=20)
updatebutton=Button(bframe,text="UPDATE",bg="#FFFF40",fg="#FFA500",command=update_command)
updatebutton.grid(row=0,column=1,padx=20)
deletebutton=Button(bframe,text="DELETE",bg="#FFFF40",fg="#FFA500",command=delete_command)
deletebutton.grid(row=0,column=3,padx=20)
clallbutton=Button(bframe,text="CLEARALL",bg="#FFFF40",fg="#FFA500",command=clearall_command)
clallbutton.grid(row=0,column=2,padx=20)

tframe = Frame(root, bg="#A5A52A")
tframe.place(x=0,y=430,width=1366,height=650)
style = ttk.Style()
style.configure("mystyle.Treeview", font=('Calibri', 18),rowheight=50)
style.configure("mystyle.Treeview.Heading", font=('Calibri', 18))
style.configure("mystyle.Treeview", font=('Calibri', 16))
tv = ttk.Treeview(tframe, columns=(1, 2, 3, 4, 5, 6, 7))
tv.heading("1", text="ID")
tv.heading("2", text="name")
tv.heading("3", text="regid")
tv.heading("4", text="contactno")
tv.heading("5", text="department")
tv.heading("6", text="gender")
tv.heading("7", text="year")
tv['show'] = 'headings'
tv.bind("<ButtonRelease-1>", getData)
tv.pack(fill=X)
displayall()
root.mainloop()